import Head from 'next/head'
import Image from 'next/image'
import { Nunito, Open_Sans } from '@next/font/google'

const nunito = Nunito({ subsets: ['latin'] })
const open_sans = Open_Sans({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={``}>
        <h3 className={nunito.className}>Halo guys</h3>
        <p className={open_sans.className}>
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Quod
          voluptates nesciunt expedita in, enim mollitia earum dolor debitis
          repellendus labore dolore nobis id rerum sint veritatis necessitatibus
          cupiditate deserunt magnam?
        </p>
      </main>
    </>
  )
}
