export const signersInitial = [
  {
    type: 'investor',
    color: 'orange',
    page: 1,
    startX: 371,
    startY: 218,
    width: 220,
    height: 100,
    canvasWidth: 933,
    canvasHeight: 1324,
  },
  {
    type: 'company_director',
    color: 'green',
    page: 1,
    startX: 338,
    startY: 878,
    width: 220,
    height: 100,
    canvasWidth: 933,
    canvasHeight: 1324,
  },
  {
    type: 'company_commissioner',
    color: 'chartreuse',
    page: 1,
    startX: null,
    startY: null,
    width: 220,
    height: 100,
    canvasWidth: 933,
    canvasHeight: 1324,
  },
  {
    type: 'kb_director',
    color: 'blue',
    page: 1,
    startX: null,
    startY: null,
    width: 220,
    height: 100,
    canvasWidth: 933,
    canvasHeight: 1324,
  },
]
