import React, { Profiler, useState } from 'react'
import { SessionProvider } from 'next-auth/react'
import {
  DesktopOutlined,
  FileOutlined,
  PieChartOutlined,
  TeamOutlined,
  UserOutlined,
  BarsOutlined,
  MoneyCollectOutlined,
  MenuUnfoldOutlined,
  MenuFoldOutlined,
} from '@ant-design/icons'
import type { MenuProps } from 'antd'
import { Breadcrumb, Layout, Menu, theme, Row, Col, Space } from 'antd'
import HeaderLayout from './header'
import Head from 'next/head'
import Link from 'next/link'
import { menuItems } from './menuItems'

const { Header, Content, Footer, Sider } = Layout

type LayoutProps = {
  children: React.ReactNode
  session: any
}

const KbLayout = ({ children, session }: LayoutProps) => {
  const [collapsed, setCollapsed] = useState(false)
  const {
    token: { colorBgContainer },
  } = theme.useToken()

  return (
    <>
      <Head>
        <title>Backoffice | Kapital Boost</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SessionProvider session={session}>
        <Layout style={{ minHeight: '100vh' }}>
          <Sider
            collapsible
            collapsed={collapsed}
            theme={'light'}
            onCollapse={() => setCollapsed(!collapsed)}
          >
            <div
              style={{
                height: 32,
                margin: 16,
                background: 'rgba(255, 255, 255, 0.2)',
              }}
            >
              {collapsed ? (
                <div className="text-center">
                  <img
                    src={`https://res.cloudinary.com/kbas/image/upload/v1562814584/logo/LOGO-19-19_has4sh.png`}
                    width={`25`}
                  />
                </div>
              ) : (
                <img
                  src={`https://res.cloudinary.com/kbas/image/upload/v1562814565/logo/LOGO-17_djoes1.png`}
                  height={23}
                />
              )}
            </div>
            <Menu
              theme="light"
              defaultSelectedKeys={['1']}
              mode="inline"
              items={menuItems}
            />
          </Sider>
          <Layout className="site-layout">
            <Header
              style={{
                padding: '0 20px',
                background: '#fff',
              }}
            >
              <HeaderLayout />
            </Header>
            <Content style={{ margin: '0 16px' }}>
              <div
                style={{
                  padding: 15,
                  marginTop: 20,
                  minHeight: 360,
                }}
              >
                {children}
              </div>
            </Content>
            <Footer style={{ textAlign: 'center' }}>
              Kapital Boost PTE LTD @2023 Created by IT Teams
            </Footer>
          </Layout>
        </Layout>
      </SessionProvider>
    </>
  )
}

export default KbLayout
